### ISSUE TITLE
Pr.2: Está usando temas avanzados de materias posteriores. 

### ISSUE THREAD

**Issue by JuanIgnGarcia** [mateodif/EstrD2022s2#11]
En esta materia no se ven foldr sino con las ideas previas a esos conceptos que está manejando, para que luego sean más naturales cuando aparezcan en la materia siguiente. No se si lo aprendiste por temas laborales o por decisión propia, pero en esta materia no se puede usar.

**Comment by mateodif** [comment]
Entendido.
