### ISSUE TITLE
Pr.2: la función elMasViejo no está hecha por recursión estructural

### ISSUE THREAD

**Issue by JuanIgnGarcia** [mateodif/EstrD2022s2#17]
Esta es una práctica de recursión estructural. La idea es usar eso, y no encontrar formas especiales para cada función…
Solamente dejamos de usar recursión estructural cuando no se puede usar…
El secreto de programar bien no es cabecear los problemas, sino entender su estructura, y usar el tiempo para los casos que sí requieren mirarlos con cuidado…

**Comment by mateodif** [comment]
Debería estar corregido ahora!

**Comment by JuanIgnGarcia** [comment]
Usa miyagi y hace recursión estructural

**Comment by mateodif** [comment]
Pero.... no está hecho con recursión estructural?
```hs
elMasViejoEntreDos :: Persona -> Persona -> Persona
elMasViejoEntreDos p1 p2 = if edadDePersona p1 > edadDePersona p2 then p1 else p2

elMasViejo :: [Persona] -> Persona
elMasViejo [p]    = p
elMasViejo (p:ps) = elMasViejoEntreDos p (elMasViejo ps)
```

**Comment by mateodif** [comment]
Creo que esto era lo que querías que haga
